FROM php:8.1-fpm
ENV CI=true

WORKDIR /var/www/html

RUN apt-get update && apt-get install unzip nano htop -y
RUN docker-php-ext-install \
    pdo_mysql
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY composer.json .
RUN composer install --no-scripts
COPY . .
RUN composer dump-autoload

RUN chown -R www-data:www-data /var/www/html
RUN chmod 775 /var/www/html/storage
